ALTER TABLE public.videos
ADD COLUMN IF NOT EXISTS layout_ratio TEXT NOT NULL DEFAULT '16:9',
ADD COLUMN IF NOT EXISTS icon_style TEXT NOT NULL DEFAULT 'rounded',
ADD COLUMN IF NOT EXISTS cover_color TEXT NULL,
ADD COLUMN IF NOT EXISTS progress_color TEXT NULL,
ADD COLUMN IF NOT EXISTS autoplay BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS show_controls BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS loop BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_live_simulator BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS feature_domain_lock BOOLEAN NOT NULL DEFAULT false;